### ISSUE TITLE
winnr() might be affected by <leader>ww but not <leader>y/pw

### ISSUE THREAD

**Issue by neur1n** [wesQ3/vim-windowswap#14]
Hello. When I use my statusline (built by following [lightline](https://github.com/itchyny/lightline.vim)) with windowsswap, I found that if I swap a text buffer with a doc buffer (for example by `:h stl`), an error occurs if I want to close the doc buffer. (See the pictures at the end. I also noticed that the `conceallevel` was also changed in the documents.

This error will not occur if I use `<leader>yw` and `<leader>pw` to swap the buffers. It seems that the `winnr()` is not `1` once I close the doc buffer, I can tell it from [lightline's code](https://github.com/itchyny/lightline.vim/blob/1ef44bfa50320347004be77f836e97dc4f54982e/autoload/lightline.vim#L24) or [mine](https://github.com/Neur1n/zipline/blob/d888c4197525473c77fb4556c5f537e68c61c4a7/autoload/zipline.vim#L27) (and the error occurs whether I use lightline or my statusline).

So I'm wondering if `<leader>ww` if different from the will-be-deprecated two, and if it is something needed to be fixed. Thanks.

![before](https://user-images.githubusercontent.com/17579247/50397494-b345aa00-07ab-11e9-9c94-0151668131e2.png)
![after](https://user-images.githubusercontent.com/17579247/50397498-b93b8b00-07ab-11e9-8944-52ca6e2795e7.png)
![close](https://user-images.githubusercontent.com/17579247/50397501-bd67a880-07ab-11e9-99e4-f410e093e984.png)

**Comment by wesQ3** [comment]
Hi, `winnr` is a value provided by vim; Windowswap doesn't set it at all, only read from it. I haven't been able to reproduce this error message without using lightline. My guess is that your statusline plugin is caching the number of windows and then overstepping the bounds of its window array after the doc window is closed.

I don't know why the mark/paste commands would not provoke this error from your plugin. As you can see in the [WS plugin](https://github.com/wesQ3/vim-windowswap/blob/master/autoload/WindowSwap.vim#L37), the easy swap command simply chooses for you whether to mark or swap based on whether you've marked a window or not.

Please reopen this issue if you can find reproduction steps for this error in Windowswap. Thanks again for reporting.

**Comment by neur1n** [comment]
Thanks for you response. I tried to use a minimal configuration to test it, now all `<leader>ww/yw/pw` makes neovim crashes. Reproduce steps:
1. Neovim: v0.3.2-dev
2. Minimal configuration as follows:
```vim
" Using vim-plug
call plug#begin('~/.config/nvim/plugged')
Plug 'wesQ3/vim-windowswap'
call plug#end()
```
3. Enter a buffer (for example an empty one, or right after startup), use `:h help` and the help buffer pops up
4. Use <leader>ww twice to swap the help buffer and the empty buffer, now the `conceallevel` of the help buffer becomes 0, and `verbose set conceallevel` only echoes 0
5. In the help buffer, use `ZZ` or `:q`
6. In my case, neovim crashes now

**Comment by wesQ3** [comment]
I'm sorry. I tried to reproduce on vim 8.0 and neovim 0.2.2 (the versions bundled with Ubuntu 18.04) and can not provoke an error.

And you are seeing neovim crash entirely, not just throw the error you saw originally? I really think this might be a problem with newer neovim. Do you see the error on regular old vim (7.3+)?

**Comment by neur1n** [comment]
It crashed entirely.

And finally I can have test on vim (8.1), nothing happened. So it seems like a neovim issue. Sorry about I didn't make a full test. Thanks for your responses.
