### ISSUE TITLE
Swapping across tabs.

### ISSUE THREAD

**Issue by trusktr** [wesQ3/vim-windowswap#5]
Relating to #4, I also often run `:echo bufnr('')` in a different tab than where I run `:b N`. Window swapping/cloning across tabs would be nice. E.g. `ww` or `yw` in one window of one tab, then `ww`, `pw`, or `cw` in a window of another tab. :D

**Comment by firedev** [comment]
I have a snippet stored in Alfred that does `:echo bufr('')`

It makes even more sense with neovim, now that you can open a terminal window and use it in a different tab.
